### ISSUE TITLE
font-family in pdf files are terrible

### ISSUE THREAD

**Issue by quant67** [moonbingbing/openresty-best-practices#111]
Hi,

After received an email describing this book this afternoon I become interested in it. But after downloading the pdf file and try to read, it is a mess.

![view-pdf](http://i11.tietuku.com/88b45ce1561aaa4b.jpg)

I know contents are most important, and people can tolerate any mistake if they really need this book. But generally, if any format error occur, readers may think that the contents of this book are also bad. So could you please rebuild it on a right way or use LaTex instead?

I really enjoy your work and wish this book could make a different. 

Best regards.

liao <liaotonglang@360.cn>

**Comment by membphis** [comment]
we dont special any font now. we dont know how to reslove this problem. i'll send you for how to reslove it by email.

great thanks.

**Comment by moonbingbing** [comment]
gitbook 使用的中文字体不适合PDF输出，会让输出看上去很怪异。这个问题已经有人给gitbook提交了issue：https://github.com/GitbookIO/gitbook/issues/532
下一个版本的gitbook应该就可以解决这个问题，换成WenQuanYi的开源字体。
