### ISSUE TITLE
4.9章节ngx.var.VARIABLE链接

### ISSUE THREAD

**Issue by orangle** [moonbingbing/openresty-best-practices#112]
现在的连接重定向到nginx Wiki首页了，也就是原来的链接失效了。

这里是github的地址 https://github.com/openresty/lua-nginx-module#ngxvarvariable

**Comment by moonbingbing** [comment]
感谢报告。可以pull request帮忙修改下吗？

2015-11-20 16:11 GMT+08:00 orangleliu <notifications@github.com>:
