### ISSUE TITLE
location 匹配规则

### ISSUE THREAD

**Issue by cywangpku** [moonbingbing/openresty-best-practices#142]
根据 nginx 的 location 匹配规则，并没有 !~ 和 !~*，这本书相关章节的解释容易误导 openresty 支持这两个规则，而事实上 openresty 仍然会报错 nginx: [emerg] invalid location modifier "!~" in ……

**Comment by cywangpku** [comment]
https://github.com/moonbingbing/openresty-best-practices/blob/master/ngx/nginx_local_pcre.md

**Comment by membphis** [comment]
抱歉回复的这么晚，已经修正，欢迎审阅。

**Comment by cywangpku** [comment]
赞！
