### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by spencer404** [moonbingbing/openresty-best-practices#156]
"Socket 编程发展"一节中,
倒数第二排应该是: "epoll 是通过内核与用户空间 mmap 同一块内存", 对吗?
"于" -> "与"

**Comment by moonbingbing** [comment]
欢迎 PR

2016-07-04 21:35 GMT+08:00 sPeng <notifications@github.com>:

**Comment by membphis** [comment]
已经 fix
