### ISSUE TITLE
openresty-best-practices/ngx_lua/timer.md

### ISSUE THREAD

**Issue by dengshiyong** [moonbingbing/openresty-best-practices#174]
1.开头的连接“请求返回后继续执行”不对，连接到了timer.md本身
2.建议写明ngx.timer.at的使用环境，比如如果想nginx启动就执行，则该函数建议放到init_worker_by_lua_block中。
3.建议补充ngx.req.*的代替方法

**Comment by membphis** [comment]
1.开头的连接“请求返回后继续执行”不对，连接到了timer.md本身（已经修正）
2.建议写明ngx.timer.at的使用环境，比如如果想nginx启动就执行，则该函数建议放到init_worker_by_lua_block中。（官方 wiki 已经有详细说明）
3.建议补充ngx.req.*的代替方法：这个没看懂您的问题。

因为这个 issue 时间比较久，暂时先关闭了。欢迎进一步交流。
