### ISSUE TITLE
mac install the openresty error

### ISSUE THREAD

**Issue by webkong** [moonbingbing/openresty-best-practices#179]
I used

```
./configure --prefix=/opt/openresty\
             --with-cc-opt="-I/usr/local/include"\
             --with-luajit\
             --without-http_redis2_module \
             --with-ld-opt="-L/usr/local/lib"
```

throw error 
You can either do not enable the modules, or install the OpenSSL library
into the system, or build the OpenSSL library statically from the source
with nginx by using --with-openssl=<path> option.

I try 

```
/configure --prefix=/opt/openresty\     
             --with-cc-opt="-I/usr/local/include"\
             --with-luajit\
             --without-http_redis2_module \
             --with-ld-opt="-L/usr/local/lib"\
--with-openssl="/usr/local/Cellar/openssl"
```

but unworked

**Comment by moonbingbing** [comment]
quote from https://openresty.org/en/installation.html

 Mac OS X (Darwin) users
You're recommended to install prerequisites PCRE and OpenSSL using some package management tool, like Homebrew:

brew update
brew install pcre openssl
Alternatively you can install PCRE and/or OpenSSL from source all by yourself :)

After installing PCRE and OpenSSL, you may need to specify the paths for their headers and libraries to your C compiler and linker, for example,

$ ./configure \
   --with-cc-opt="-I/usr/local/opt/openssl/include/ -I/usr/local/opt/pcre/include/" \
   --with-ld-opt="-L/usr/local/opt/openssl/lib/ -L/usr/local/opt/pcre/lib/" \
   -j8
assuming that your PCRE and OpenSSL are installed under the prefix /usr/local/opt/ which is the default for homebrew.

**Comment by smartwjw** [comment]
mac 使用 homebrew 安装挺好的。

```bash
brew install openresty
```

**Comment by moonbingbing** [comment]
Is OpenResty in homebrew  maintained by official？

**Comment by agentzh** [comment]
@moonbingbing Nope. Can we grab it?

**Comment by agentzh** [comment]
@smartwjw Be careful that the openresty brew is not official.

I always want to grab that brew, polish it up, and make it official.

**Comment by moonbingbing** [comment]
sure. I will do that

2016-12-16 9:11 GMT+08:00 Yichun Zhang <notifications@github.com>:

**Comment by smartwjw** [comment]
@agentzh @moonbingbing Although openresty brew is not official, the download source of the tarball is from openresty.org, see [homebrew-nginx/Formula/openresty.rb](https://github.com/Homebrew/homebrew-nginx/blob/master/Formula/openresty.rb) for more details.

**Comment by moonbingbing** [comment]
yes, we can fork this great project and contribute some PRs to make it
better.

2016-12-16 9:54 GMT+08:00 Junwei Wang <notifications@github.com>:

**Comment by agentzh** [comment]
@smartwjw Using OpenResty's official source tarball is not enough. We also need our own openssl component to enable those advanced features like `ssl_session_fetch_by_lua*` and `ssl_session_store_by_lua*`. And there are also special build flags and etc used in our official Linux binary packages:

https://github.com/openresty/openresty-packaging

**Comment by smartwjw** [comment]
@agentzh Got it, its may be a good idea to send some PRs to that project.
