### ISSUE TITLE
表格为什么要转成图片

### ISSUE THREAD

**Issue by hbrls** [moonbingbing/openresty-best-practices#180]
这样并不利于搜索

**Comment by membphis** [comment]
这是个历史问题了，当时最佳实践要上线 微信读书 ，微信读书的排班有问题，所以我们临时修改成了图片。
不过后面发现微信图书对于这类纯技术类支持不是很好，现在看可以回滚了。

**Comment by hbrls** [comment]
那就回滚一下吧，要 pr 么

**Comment by membphis** [comment]
欢迎 PR 。在指定文件中查看 git log就能找到对应的 commit id，把他 revert 一下就可以

**Comment by membphis** [comment]
已经合并 PR
