### ISSUE TITLE
cosokect的疑问

### ISSUE THREAD

**Issue by zzctmac** [moonbingbing/openresty-best-practices#182]
在看《怎样理解 cosocket》一章中，看到如下解释：
> 用户的 Lua 脚本每触发一个网络操作，都会触发一个协程的 yield 以及 resume，因为每个请求的 Lua 脚本实际上都运行在独享协程之上，可以在任何需要的时候暂停自己（yield），也可以在任何需要的时候被唤醒（resume）。

那么我可不可以理解为：
在一个请求处理的过程中，前一个网络请求等待（暂停了自己）的时候下一个网络请求还是得等着（唤醒以后往下执行）？

**Comment by spacewander** [comment]
从单个请求的视角看，的确如此。
用银行排队的比喻：
当客户发起一个请求时，他会一直等，直到自己的号被叫到。叫到号之后，再进行下一步的工作。

如果以服务器（银行柜员）的视角看，她一直都是在忙碌着的。

**Comment by zzctmac** [comment]
也就是说单独一个请求来看，并不如体现cosocket的优点，只有在多个请求的情况下，cosoket优点才能展示出来

**Comment by spacewander** [comment]
对，如果这样回答了你的问题，可以考虑关闭这个 issue 了。

**Comment by zzctmac** [comment]
谢谢
