### ISSUE TITLE
关于 consocket 的描述

### ISSUE THREAD

**Issue by xiaooloong** [moonbingbing/openresty-best-practices#183]
文中多次表述 consocket 是 “异步非阻塞”

而 `ngx.socket` 的各种操作却是同步的，又根据文档描述，`ngx.socket` 应该是同步非阻塞的

**Comment by zzctmac** [comment]
你是说它的使用上是同步(没有回调函数)的对吗？

**Comment by membphis** [comment]
文中说的 cosocket 就是 `ngx.socket.*` ，外在暴露书写形式是同步方式。但是内部运行机制是 异步非阻塞 的。

也就是说用同步的方式写代码，但是他本质上的执行却是 异步非阻塞  的，这也是 openresty 巧妙的地方，让开发者更容易上手。

**Comment by moonbingbing** [comment]
摘自春哥官方回复：
all the cosocket operations are synchronous operations while they also do
not block any operating system threads. And they are also using nonblocking
I/O.
所以 cosocket 是同步操作，但是没有阻塞任何操作系统的线程。

在 2016年11月29日 下午4:49，YuanSheng Wang <notifications@github.com>写道：

**Comment by xiaooloong** [comment]
@moonbingbing 确实是同步的，还是把文中的异步改成同步吧

**Comment by moonbingbing** [comment]
@membphis 修改下https://github.com/moonbingbing/openresty-best-practices/blob/ce2e94927b60aca1b335bacdabfbb44a8a2ade58/ngx_lua/whats_cosocket.md，里面很多概念有偏差
