### ISSUE TITLE
防止SQL注入的%s应该不需要用单引号，不确定是否还有其他情况需要考虑？

### ISSUE THREAD

**Issue by hanxi** [moonbingbing/openresty-best-practices#184]
https://moonbingbing.gitbooks.io/openresty-best-practices/content/openresty/safe_sql.html
```
db:query(string.format([[select * from cats where id = '%s']],
    ndk.set_var.set_quote_sql_str(req_id)))
```
跟下面的不一样，`set_quote_sql_str` 和 `quote_sql_str` 结果都会给参数加上单引号。
https://github.com/openresty/lua-resty-mysql#sql-literal-quoting
```
local name = ngx.unescape_uri(ngx.var.arg_name)
local quoted_name = ngx.quote_sql_str(name)
local sql = "select * from users where name = " .. quoted_name
```

**Comment by hanxi** [comment]
这里也是没自己加单引号的
https://moonbingbing.gitbooks.io/openresty-best-practices/content/postgres/sql_inject.html
```
local sql_normal = [[select id, name from user where name=]] .. name .. [[ and password=]] .. password .. [[ limit 1;]]
```

**Comment by membphis** [comment]
非常感谢问题报告，已经修复
