### ISSUE TITLE
360里面都用lua？

### ISSUE THREAD

**Issue by lidaohang** [moonbingbing/openresty-best-practices#2]
没发现很特别的东西，都是些lua代码啥的，感觉含量不高，哈哈~

**Comment by aifeiasdf** [comment]
都是在实现360业务中解决的一些问题或者说遇到的一些坑，这种开发模式或者说openresty这个框架的优越性我们是比较认可的，所以打算共享一些填坑的经验，方便其它openresty框架的爱好者一起参与并改进

**Comment by lidaohang** [comment]
明白，感谢分享经验~  互相学习学习~
