### ISSUE TITLE
也许没有必要再在 Windows 上使用 dkjson 了

### ISSUE THREAD

**Issue by spacewander** [moonbingbing/openresty-best-practices#210]
现在 OpenResty 官方的 cjson 库已经支持在 Windows 平台下编译，
json 这一章下面 《跨平台的库选择》似乎可以废弃掉了？
https://github.com/moonbingbing/openresty-best-practices/blob/master/json/cross_os.md

**Comment by membphis** [comment]
这个倒是，欢迎 PR
