### ISSUE TITLE
reverse_proxy.cd 中有个链接失效了

### ISSUE THREAD

**Issue by NominationP** [moonbingbing/openresty-best-practices#220]
```
(1) location

location 项对请求 URI 进行匹配，location 后面配置了匹配规则。例如上面的例子中，如果请求的 URI 是 localhost/，则会匹配 location / 这一项；如果请求的 URI 是 localhost/README.md，则会匹配 location /README.md 这项。

上面这个例子只是针对一个确定的 URI 做了反向代理，有的读者会有疑惑：如果对每个页面都进行这样的配置，那将会大量重复，能否做 批量 配置呢？此时需要配合使用 location 的正则匹配功能。具体实现方法可参考本书的 **URL 匹配章节**。
```

**Comment by spacewander** [comment]
@NominationP 
谢谢纠错。已经把失效的链接指向 Nginx 官方文档上关于 location 的描述了。
http://nginx.org/en/docs/http/ngx_http_core_module.html#location

**Comment by NominationP** [comment]
你好，关于nginx反向代理，匹配url有个问题想请教下

这样完全匹配是可以的
https://XXXX/laravel

    location /laravel {

        proxy_pass http://dockone.io/article;

    }

靠参数来找，就失败了，显示 502
https://XXXX/laravel/296
Bad Gateway
    location ~* ^/laravel/(.*) {

        proxy_pass http://dockone.io/article/$1$is_args$args;

    }



2017-09-06 9:50 GMT+08:00 罗泽轩 <notifications@github.com>:

**Comment by NominationP** [comment]
通过日志看到错误 no resolver defined to resolve
然后加了一行 resolver 8.8.8.8; 就好了
之前没看日志就问您是因为日志太满了，根本打不开，又设置了一下日志的路径，才看到。。。。。。。
打扰了！

在 2017年9月6日 下午2:33，ze zhang <zhangze1029@gmail.com>写道：
