### ISSUE TITLE
当把flush_limit设置为1的时候，在高并发的情况也会存在日志丢失的情况。

### ISSUE THREAD

**Issue by JoyChou93** [moonbingbing/openresty-best-practices#222]
https://moonbingbing.gitbooks.io/openresty-best-practices/content/ngx_lua/log.html

在使用resty-logger记录日志时，当把flush_limit设置为1的时候，在高并发的情况也会存在日志丢失的情况。

**Comment by agentzh** [comment]
@JoyChou93 当你把 flush_limit 置得很小时，发送请求的频度会提高很多倍。而当你的接收后端来不及接收和处理这么密集的发送请求时，openresty 一侧就只能积压日志，积压到 buffer 的上限，自然只能丢弃日志了。所以当你设置 flush_limit 为 1 时，最好清楚自己在做什么……

**Comment by JoyChou93** [comment]
@agentzh 我把flush_limit设置为4096，在log阶段 用resty-logger记录日志，高并发的情况，也会丢失日志。`ab -n 30000 -c 100`

**Comment by agentzh** [comment]
@JoyChou93 你应该先确定你的日志接收端的吞吐能力的极限。如果对端来不及接收，肯定必须得丢。如果你认为是 lua-resty-logger-socket 的 bug，那么你需要提供足够的细节和证据。
