### ISSUE TITLE
【建议】反向代理：nginx示例配置 修改 监听端口为8866

### ISSUE THREAD

**Issue by shuiRong** [moonbingbing/openresty-best-practices#223]
[反向代理](https://github.com/moonbingbing/openresty-best-practices/blob/master/ngx/reverse_proxy.md)
第一遍尝试反向代理没有成功，检查了一下才发现原来nginx示例配置中监听的是80端口，但成功截图中访问的却是8866端口。

（问题虽小，但可能有些不理解的人（只是想学着做时）就会跑不通...）

**Comment by spacewander** [comment]
确实有必要保持一致。你来修改一下，发个 pull request？

**Comment by shuiRong** [comment]
已发起PR
