### ISSUE TITLE
虚变量表述不准确

### ISSUE THREAD

**Issue by wmzy** [moonbingbing/openresty-best-practices#224]
> Lua 提供了一个虚变量(dummy variable)，以单个下划线（“_”）来命名，用它来丢弃不需要的数值，仅仅起到占位的作用。

这个表述让人觉得`_`是一个特殊的变量,其实它只是一个[命名惯例](https://www.lua.org/pil/1.3.html),和golang里的`_`完全不是一回事.

**Comment by spacewander** [comment]
@wmzy 
谢谢指正。能否提个 pull request，更正这一段内容呢？

**Comment by wmzy** [comment]
可以,我试试吧.
