### ISSUE TITLE
how get $prefix  variable in lua script

### ISSUE THREAD

**Issue by suifengpiao14** [moonbingbing/openresty-best-practices#227]
how can i get the $prefix (lua_package_path ";;$prefix/?.lua;";) variable in lua file

**Comment by spacewander** [comment]
`$prefix` 这个其实不是 Nginx 变量，ngx_lua 在处理 `lua_package_path` 会把它展开成实际的前缀。
在 Lua 代码里可以用 `ngx.config.prefix()` 这个函数获取到同样的值。

**Comment by suifengpiao14** [comment]
谢谢你，解决了我的问题
