### ISSUE TITLE
lj-lua-stacks.sxx 出错

### ISSUE THREAD

**Issue by samuelyao314** [moonbingbing/openresty-best-practices#237]
我的环境:  centos 7,  OpenResty 1.15.8.1 

[root@localhost workspace]# lj-lua-stacks.sxx --arg time=10 --skip-badvars -x  18767
Found exact match for libluajit: /home/samuelyao/openresty/luajit/lib/libluajit-5.1.so.2.1.0
semantic error: while processing function luajit_G

semantic error: unable to find member 'ptr32' for struct MRef (alternatives: ptr64): operator '->' at stapxx-cyF6xeHE/luajit.stp:162:103
        source:     return @cast(L, "lua_State", "/home/samuelyao/openresty/luajit/lib/libluajit-5.1.so.2.1.0")->glref->ptr32

**Comment by moonming** [comment]
这个是 OpenResty 新版本和 stap 工具的兼容性问题，需要官方来解决

**Comment by membphis** [comment]
本地手工编译 openresty ，禁用掉 GC64 model 模式
