### ISSUE TITLE
openresty的库函数文档下载链接失效

### ISSUE THREAD

**Issue by Sanit1** [moonbingbing/openresty-best-practices#241]
章节目录：Lua编辑器选择 进阶配置

> 由于emmylua并没有自带openresty的库函数,所以我们需要自己写函数提示,这里我提供我自己写的供你们下载和丰富.请丢到你的lualib根目录中

这里的下载链接失效

**Comment by membphis** [comment]
欢迎再次确定是否已经修正，如果没修正欢迎 PR 修复
