### ISSUE TITLE
Adding English translation

### ISSUE THREAD

**Issue by smart-developerr** [moonbingbing/openresty-best-practices#242]
Hi!
Thanks for your awesome repo! Please add English translation to help other than Chinese developers

**Comment by wanghaisheng** [comment]
Just upload original pdf to google document translate , you can get a fine English version,may be not perfect

**Comment by smart-developerr** [comment]
Please comment the original pdf link.

**Comment by wanghaisheng** [comment]
as you know  this one is pushlised on gitbook
http://moonbingbing.gitbooks.io/openresty-best-practices/content/index.html
you can download the latest version from there

**Comment by smart-developerr** [comment]
Thank you!
