### ISSUE TITLE
pdf版本的问题

### ISSUE THREAD

**Issue by asdog** [moonbingbing/openresty-best-practices#3]
貌似pdf的有不少的空白页？有的话，可以提供最新的pdf版本么？

**Comment by moonbingbing** [comment]
很多是只列了目录，还没有填充内容。我们会在最近一两个月内，把大部分内容完成。

**Comment by onlyfew** [comment]
请问哪里有pdf下载链接，我没找到。。。

**Comment by membphis** [comment]
https://www.gitbook.com/book/moonbingbing/openresty-best-practices

这里就有的。

On Sun, Dec 6, 2015 at 11:21 PM, onlyfew <notifications@github.com> wrote:

> 请问哪里有pdf下载链接，我没找到。。。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moonbingbing/openresty-best-practices/issues/3#issuecomment-162323315>
> .
>



-- 

*MembPhis*
My github: https://github.com/membphis
Our Book: OpenResty Best Practices
<https://www.gitbook.com/book/moonbingbing/openresty-best-practices>

**Comment by onlyfew** [comment]
谢谢~~
