### ISSUE TITLE
优化：require写法规范化

### ISSUE THREAD

**Issue by Miss-you** [moonbingbing/openresty-best-practices#332]
不建议的写法：

```
local redis = require "resty.redis"
```

建议写法

```
local redis = require("resty.redis")
```

**Comment by membphis** [comment]
这里没有正确和错误的说法，是个风格喜好问题。

有些人喜欢极简，能少写一行，就不多写。
我则更喜欢不用猜，代码易读。所以我更希望 lua 里使用下面的写法

**Comment by Miss-you** [comment]
> 这里没有正确和错误的说法，是个风格喜好问题。
> 
> 有些人喜欢极简，能少写一行，就不多写。
> 我则更喜欢不用猜，代码易读。所以我更希望 lua 里使用下面的写法

我觉得应该统一，而不是两种都有。最佳实践是咱们的经验，那么风格上也应该遵循我们自己的喜好

**Comment by Miss-you** [comment]
> 这里没有正确和错误的说法，是个风格喜好问题。
> 
> 有些人喜欢极简，能少写一行，就不多写。
> 我则更喜欢不用猜，代码易读。所以我更希望 lua 里使用下面的写法

将正确和错误改为建议和不建议
