### ISSUE TITLE
建议 iResty 组织收书

### ISSUE THREAD

**Issue by ZoomQuiet** [moonbingbing/openresty-best-practices#35]
这书明显是必须长期持续增补的
现在私人仓库不合适协同维护
建议及时创建 iResty 组织,
将春哥等拉入,
变成一个社区项目.

**Comment by membphis** [comment]
我们的确有这个考虑，我们想把它做的更完善一些后，再把它做成组织。比较好的是github本身就支持pull request，欢迎大家pr一起协作。

**Comment by moonbingbing** [comment]
已经在github成立了iresty组织，稍后会把书和网站转移到这个组织下
