### ISSUE TITLE
Lua 代码在被执行之前总是会先被 lfn 成 LuaJIT 自己定义的字节码?

### ISSUE THREAD

**Issue by katepangLiu** [moonbingbing/openresty-best-practices#351]
Lua 代码在被执行之前总是会先被 lfn 成 LuaJIT 自己定义的字节码
https://moonbingbing.gitbooks.io/openresty-best-practices/content/lua/what_jit.html
这里面的 lfn 是表达什么意思？是错别字吗？

**Comment by membphis** [comment]
欢迎提交 PR 修复
